### ISSUE TITLE
Q1 2021 Roadmap

### ISSUE THREAD

**Issue by martonlanga** [TermyApp/termy#84]
- [x] rewrite (#46, #71, #59) 
- [x] windows & Linux support (#30, #31)
- [x] paths with spaces (#36)
- [x] keyboard navigation (#35)
- [x] internal history (#19)
- [x] prompt (#82) 
- [x] refactor (#93)
- [x] tokenizer fixes (#80)
- [x] app logger & perf.measure
